from typing import Any, Awaitable, Optional

class EpisodeRole:
    User: "EpisodeRole"
    Assistant: "EpisodeRole"
    System: "EpisodeRole"

    def __init__(self, role: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class MemoryType:
    Episodic: "MemoryType"
    Semantic: "MemoryType"

    def __init__(self, memory_type: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class EpisodeEntry:
    role: EpisodeRole
    content: str
    name: Optional[str]
    metadata: Optional[Any]

    def __init__(
        self,
        role: EpisodeRole,
        content: str,
        name: Optional[str] = None,
        metadata: Optional[Any] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Episode:
    @property
    def uid(self) -> str: ...
    @property
    def session_key(self) -> str: ...
    @property
    def role(self) -> EpisodeRole: ...
    @property
    def content(self) -> str: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def metadata(self) -> Optional[Any]: ...
    @property
    def created_at(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    def __repr__(self) -> str: ...

class SessionData:
    session_key: str
    user_profile_id: Optional[str]
    role_profile_id: Optional[str]
    session_id: Optional[str]

    def __init__(
        self,
        session_key: str,
        user_profile_id: Optional[str] = None,
        role_profile_id: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class SessionInfo:
    @property
    def session_key(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def created_at(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    def __repr__(self) -> str: ...

class Session:
    @property
    def session_key(self) -> str: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def configuration(self) -> Optional[Any]: ...
    @property
    def metadata(self) -> Optional[Any]: ...
    @property
    def created_at(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    def __repr__(self) -> str: ...

class FeatureMetadata:
    @property
    def id(self) -> str: ...
    @property
    def citations(self) -> Optional[list[str]]: ...
    @property
    def other(self) -> Optional[Any]: ...
    @property
    def created_at(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    def __repr__(self) -> str: ...

class SemanticFeature:
    @property
    def set_id(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def tag(self) -> str: ...
    @property
    def feature_name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def metadata(self) -> FeatureMetadata: ...
    def __repr__(self) -> str: ...

class EpisodicSearchResult:
    @property
    def episodes(self) -> list[Episode]: ...
    @property
    def scores(self) -> list[float]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

class SearchResponse:
    @property
    def episodic_memory(self) -> Optional[EpisodicSearchResult]: ...
    @property
    def semantic_memory(self) -> Optional[list[tuple[SemanticFeature, float]]]: ...
    def __repr__(self) -> str: ...

class ListResults:
    @property
    def episodic_memory(self) -> Optional[list[Episode]]: ...
    @property
    def semantic_memory(self) -> Optional[list[SemanticFeature]]: ...
    def __repr__(self) -> str: ...

class MemMachine:
    def __init__(
        self, storage_path: str, config_path: Optional[str] = None
    ) -> None: ...
    def start(self) -> Awaitable[None]: ...
    def stop(self) -> Awaitable[None]: ...
    def is_started(self) -> bool: ...
    def create_session(
        self, session_key: str, description: str
    ) -> Awaitable[SessionInfo]: ...
    def get_session(self, session_key: str) -> Awaitable[Optional[Session]]: ...
    def delete_session(self, session_data: SessionData) -> Awaitable[None]: ...
    def search_sessions(
        self, filter: Optional[dict[str, Any]] = None
    ) -> Awaitable[list[str]]: ...
    def add_episodes(
        self,
        session_data: SessionData,
        entries: list[EpisodeEntry],
        target_memories: Optional[list[MemoryType]] = None,
    ) -> Awaitable[list[str]]: ...
    def query_search(
        self,
        session_data: SessionData,
        query: str,
        target_memories: Optional[list[MemoryType]] = None,
        limit: Optional[int] = None,
        min_score: Optional[float] = None,
    ) -> Awaitable[SearchResponse]: ...
    def list_search(
        self,
        session_data: SessionData,
        target_memories: Optional[list[MemoryType]] = None,
        filter: Optional[dict[str, Any]] = None,
        page_size: Optional[int] = None,
        page_num: Optional[int] = None,
    ) -> Awaitable[ListResults]: ...
    def episodes_count(
        self,
        session_data: SessionData,
        filter: Optional[dict[str, Any]] = None,
    ) -> Awaitable[int]: ...
    def delete_episodes(
        self,
        episode_ids: list[str],
        session_data: Optional[SessionData] = None,
    ) -> Awaitable[int]: ...
    def delete_features(self, feature_ids: list[str]) -> Awaitable[int]: ...
    def add_semantic_feature(
        self,
        session_data: SessionData,
        category: str,
        tag: str,
        feature_name: str,
        value: str,
    ) -> Awaitable[str]: ...
    def __repr__(self) -> str: ...

__version__: str
